import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Amplify } from "aws-amplify";
import amplifyconfiguration from "../amplifyconfiguration.json";

Amplify.configure({
  ...amplifyconfiguration,
  API: {
    REST: {
      chargebot: {
        endpoint: process.env.API_URL ?? "",
      }
    }
  },
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
